# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "tvinhas/ubuntu-16.04-hyperv"
    config.vm.provision "shell", path: "provision/node.sh", privileged: true

    # Managers
    (1..1).each do |number|
        config.vm.define "m#{number}" do |node|
            node.vm.network "public_network", ip: "10.0.0.20#{number}", bridge: "Wireless LAN adapter Wi-Fi"
            node.vm.hostname = "m#{number}"
        end  
    end

    # Workers
    (1..3).each do |number|
        config.vm.define "w#{number}" do |node|
            node.vm.network "public_network", ip: "10.0.0.21#{number}", bridge: "Wireless LAN adapter Wi-Fi"
            node.vm.hostname = "w#{number}"
        end  
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096 
        v.cpus = 2
    end

end